### ISSUE TITLE
大佬想问下 问题解决了吗 怎么解决的呢   如果主应用和子应用都用vite5有问题吗

### ISSUE THREAD

**Issue by weizhigang55** [Ttou/wujie-issue#1]

**Comment by Ttou** [comment]
之前主应用试过vite是不行的，我自己搭建的模板主应用一直是 vue-cli，你可以试试；或者主应用基于 rsbuild 搭建看看，没试过

**Comment by weizhigang55** [comment]
大佬想问下，主应用不可以vite的原因是因为样式问题还是，我看你的例子使用vite2.9正常的是

**Comment by Ttou** [comment]
这个问题没关注了
